spring.application.name=kiraouj
#spring.datasource.url=jdbc:sqlite:./data.db
spring.datasource.url=${DATABASE_URL}
spring.datasource.driverClassName=org.sqlite.JDBC
spring.exposed.generate-ddl=true
spring.exposed.show-sql=true

